### ISSUE TITLE
"Production" series override in Grafana ?

### ISSUE THREAD

**Issue by pagaille** [lewei50/Solar-PV-Monitoring#4]
Hi

Thanks for your nicely crafted Grafana panel which is very inspiring.

Question however : Why does each hourly and monthly graphs have a "Production" series override regarding properties like Bars, Lines, etc ? copy paste error ? What was the idea behind it ? 

![image](https://user-images.githubusercontent.com/1886799/159257358-8e5ff0d9-1bd7-4ecd-beae-748a7c018773.png)

Txs

**Comment by miwyf** [comment]
not used you can delete

**Comment by miwyf** [comment]
> 你好
> 
> 感谢您精心制作的Grafana面板，这非常鼓舞人心。
> 
> 然而，问题：为什么每个小时和每月图表都有一个关于柱线，线等属性的"生产"系列覆盖？复制粘贴错误 ？它背后的想法是什么？
> 
> ![图像](https://user-images.githubusercontent.com/1886799/159257358-8e5ff0d9-1bd7-4ecd-beae-748a7c018773.png)
> 
> 断续器
