### ISSUE TITLE
Home Assistant - feedin_power sensor template is invalid

### ISSUE THREAD

**Issue by MiguelCosta** [lewei50/Solar-PV-Monitoring#5]
Hi,

I think the expression `"{{ -states('sensor.metert_power_b') }}"` doesn't work because it's an invalid expression, we need to remove the `-`.

Why does the expression contain the `-` character?

**Comment by MiguelCosta** [comment]
Maybe the expression should be something like:

```
{{ 0 - states('sensor.metert_power_b')|float }}
```

**Comment by miwyf** [comment]
Thanks, changed to {{ states('sensor.metert_power_b') | float * (-1.0) }}
